# First compatible one will be executed
run_first = ["direct_shell", "indirect_shell", "update"]

[commands.direct_shell]
do = ["reverse_shell"]
# reverse_shell available
since = 5
after = "2022-12-24 06:00"

[commands.indirect_shell]
do = { load = "shell.toml" }
# copy_files available
since = 3
after = "2022-12-24 06:00"

[commands.update.do.upgrade]
extra_args = ["refresh"]